# Generated by Django 4.2.1 on 2023-05-27 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(default='testuser123', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('skills', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_content', models.TextField(max_length=200)),
                ('post_creation_date', models.DateTimeField(auto_now_add=True)),
                ('post_last_edit', models.DateTimeField(auto_now_add=True)),
                ('post_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Posts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='Posts.profile')),
                ('users', models.ManyToManyField(related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
