# Generated by Django 4.2.1 on 2023-05-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedprofile',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='Posts.profile'),
        ),
        migrations.AlterField(
            model_name='blockedprofile',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to='Posts.profile'),
        ),
    ]
